from listas_2022 import *
lista_prueba = ListaCircular()
print("Lista:",lista_prueba)
lista_prueba.adicionarAlInicio(10)
print("Lista:",lista_prueba)
lista_prueba.adicionarAlInicio(30)
print("Lista:",lista_prueba)
lista_prueba.adicionarAlFinal(50)
print("Lista:",lista_prueba)
lista_prueba.adicionarAlFinal(3)
print("Lista:",lista_prueba)
lista_prueba.eliminarInfo(50)
print("Lista:",lista_prueba)
lista_prueba.eliminarInfo(30)
print("Lista:",lista_prueba)
lista_prueba.eliminarInfo(3)
print("Lista:",lista_prueba)
lista_prueba.eliminarInfo(10)
print("Lista:",lista_prueba)
