from grafos_dijkstra2023 import GrafoLista
grafo01 = GrafoLista()
#Adicionar vértices
grafo01.adicionarVertice("BOS")
grafo01.adicionarVertice("JFK")
grafo01.adicionarVertice("ORD")
grafo01.adicionarVertice("DFW")
grafo01.adicionarVertice("MIA")
grafo01.adicionarVertice("SFO")
grafo01.adicionarVertice("LAX")
# #Adicionar arcos
grafo01.adicionarArco("BOS", "JFK")
grafo01.adicionarArco("BOS", "MIA")
grafo01.adicionarArco("JFK", "MIA")
grafo01.adicionarArco("JFK", "DFW")
grafo01.adicionarArco("JFK", "SFO")
grafo01.adicionarArco("DFW", "ORD")
grafo01.adicionarArco("DFW", "LAX")
grafo01.adicionarArco("ORD", "DFW")
grafo01.adicionarArco("LAX", "ORD")
grafo01.adicionarArco("MIA", "DFW")
grafo01.adicionarArco("MIA", "LAX")
print("El grafo es:\n",grafo01, sep="")
print("DFS BOS:",grafo01.recorrerProfundidad("BOS"))
print("DFS SFO:",grafo01.recorrerProfundidad("SFO"))
print("BFS JFK:",grafo01.recorrerAnchura("JFK"))